In [4]:
import numpy as np

Creacion de numpies

A partir de una lista

In [5]:

lista = [1,2,3,4,5,6,67]

numpyLista = np.array(lista)

print(numpyLista)

[ 1  2  3  4  5  6 67]


Atraves de un rango

In [7]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


Operaciones con numpy

In [9]:
# Sumar le un 1 a todo el arreglo
array = array + 1
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# Elevar al cuadrado todos los elementos
array_cuadrado = array**2
print(array_cuadrado)
print(array) # el elemento array no se ve afectado

[  1   4   9  16  25  36  49  64  81 100]
[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# Sumar todos los elemntos del arreglo

print(array_cuadrado.sum())

385


In [15]:
# Mascara extraer ciertos valores del arreglo que cumplan una condicion

mask = array % 2 == 0 
array_3 = array[mask]
print(mask)
print(array_3)

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


In [18]:
# Remplasar ciertos valores que cumplanuna condicionpor una letra

array[array % 2 == 0] = -1

array

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1])

In [20]:
#Remplzar valores sin que el aareglo original se vea afectado

numeros = np.arange(11)
out = np.where(numeros % 2 == 0,-50,numeros)

print(numeros)
print(out)

[ 0  1  2  3  4  5  6  7  8  9 10]
[-50   1 -50   3 -50   5 -50   7 -50   9 -50]


In [27]:
arreglo = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])

print(arreglo)
print(arreglo.shape)




[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
(3, 6)


In [32]:
# Remodelar un arreglo

arr = np.arange(10)
arr = arr.reshape(2,-1)

arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
# Apilamiento de dos arreglos verticales

a = np.arange(10).reshape(2,-1)
b = np.repeat(2,10).reshape(2,-1)

c = np.vstack([a,b])

print(a)
print()
print(b)
print()
print(c)


[[0 1 2 3 4]
 [5 6 7 8 9]]

[[2 2 2 2 2]
 [2 2 2 2 2]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [46]:
# Apilamiento de dos arreglos horizontales

d = np.hstack([a,b])
d

array([[0, 1, 2, 3, 4, 2, 2, 2, 2, 2],
       [5, 6, 7, 8, 9, 2, 2, 2, 2, 2]])

In [48]:
# Dados dos arreglos obtener los datos que tienen en comun

a = np.array([1,2,3,4,5,6,6,7,8]) 
b = np.array([1,56,7,6,0,6])

c = np.intersect1d(a,b)
print(c)

[1 6 7]


In [50]:
# Como remover de un arreglo aquellos numeros que existen en el otro

a = np.array([1,2,3,4,5,6,6,7,8]) 
b = np.array([1,56,7,6,0,6])

c = np.setdiff1d(b,a)# el primer elemnto es el arreglo donde se remueven los numeros

print(c)

[ 0 56]


In [62]:
# Obtencion de las posiciones de los elemntos donde coinciden
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.where(a==b)


print(c)

(array([1, 3, 5, 7], dtype=int64),)


In [53]:
# Obtencion de numeros dentro de un rango en especifico

a = np.array([2,6,1,9,10,3,27,15,17])

index = np.where( (a>=5) & (a<=20) )

print(a[index])

[ 6  9 10 15 17]


In [64]:
# Como hacer una funcion que maneje escalares para trabajar en numpy

def maxx(x,y):

    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx,otypes = [int])#or float or double)


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [69]:
# Como intercambiar dos columnas en un arreglo numpy de dos dimensiones

arr = np.arange(9).reshape(3,3)
print(arr)
print()

arr = arr [:,[2,1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [77]:
# Como intercambiar dos filas en un arreglo numpy de dos dimensiones

arr = np.arange(9).reshape(3,3)
print(arr)
print()

arr = arr [[1,0,2],:]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [79]:
#Como reversar las filas del arreglo

arr = np.arange(9).reshape(3,3)
print(arr)
print()
print(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [80]:
#Como reversar las columnas del arreglo

arr = np.arange(9).reshape(3,3)
print(arr)
print()
print(arr[:,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [86]:
# Creacion de un arreglo 2D que contenga numeros random flotantes entre 5 y 10

rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[7.34939191 9.7116423  9.35401833]
 [8.9240811  5.99877567 6.70929343]
 [9.02502937 5.25693315 6.60424462]
 [7.53397728 5.84948305 8.18609021]
 [7.21924429 9.47964312 6.5066653 ]]


In [130]:
# Como imprimir solo tres decimales enun arreglo 
# Funcion random solos son numeros del 0 al 1

ran_arr = np.random.random([5,3])

ran_arr = np.set_printoptions(precision = 3)
print(rand_arr[:])


[[7.349 9.712 9.354]
 [8.924 5.999 6.709]
 [9.025 5.257 6.604]
 [7.534 5.849 8.186]
 [7.219 9.48  6.507]]


In [132]:
#Comoimportar un dataset con numeros y texto
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:5]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)